on:
  workflow_run:
    workflows: [".NET CI with Publish"]
    branches: [main]
    types: [completed]

name: Dev - Deploy to Amazon ECS

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ap-southeast-2
      with:
        aws-access-key-id: $AWS_ACCESS_KEY_ID
        aws-secret-access-key: $AWS_SECRET_ACCESS_KEY
        aws-region: $AWS_REGION

    - name: Fill in the new image ID in the Amazon ECS task definition
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      env:
        TASK_DEFINITION_FILE: aws-ecs-task-definition.json
        CONTAINER_NAME: battleship-state-tracker
        IMAGE_NAME: romlozano/battleship-state-tracker:latest
      with:
        task-definition: $TASK_DEFINITION_FILE
        container-name: $CONTAINER_NAME
        image: $IMAGE_NAME

    - name: Deploy Amazon ECS task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      env:
        SERVICE_NAME: battleship-state-tracker
        CLUSTER_NAME: battleship-state-tracker
      with:
        task-definition: ${{ steps.task-def.outputs.task-definition }}
        service: $SERVICE_NAME
        cluster: $CLUSTER_NAME
        wait-for-service-stability: true
